FROM python:3.12-slim-bookworm

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends openssh-client sshpass && \
    apt autoremove -y && \
    apt clean -y && \
    rm -rf /var/lib/apt/lists/*

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

WORKDIR /app

RUN pip install pip --upgrade

# --user configures for the current user instead of root: "pip install --user ansible"
RUN pip install ansible

# ENV PATH="/home/appuser/.local/bin:${PATH}"

# Additional Ansible configuration
RUN mkdir -p /home/appuser/.ssh && \
    mkdir -p /home/appuser/.ansible/roles /home/appuser/.ansible/tmp 